### ISSUE TITLE
No longer working any more on the latest iTunes(renamed to Music) v1.0.5.14

### ISSUE THREAD

**Issue by donly** [hisaac/LEDSA#2]
The source code is too old, not the latest version I think.
so sad..

**Comment by hisaac** [comment]
Yeah, you definitely could be right. As far as I know, this was the only version the developer open sourced, so it's all we have. It hasn't been working for over 4 years at this point. 😞

**Comment by hisaac** [comment]
Closing this for now, as it's a known issue, but feel free to reopen if you have any insight into how to address the issue. Thank you.
